/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Interna.Tela_OperacaoDoisNumeros;
import Interna.Tela_OperacaoUmNumero;
import javax.swing.JOptionPane;

/**
 *
 * @author williank
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGrafica
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        DesktopCalculadora = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuOperacoes = new javax.swing.JMenu();
        opcaoMenu_UmNumero = new javax.swing.JMenuItem();
        opcaoMenu_DoisNumeros = new javax.swing.JMenuItem();
        MenuOpcoes = new javax.swing.JMenu();
        opcaoMenu_Sair = new javax.swing.JMenuItem();
        opcaoMenu_Sobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Gráfica - Desenvolvido por Willian Rosa");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/desktop.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        DesktopCalculadora.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopCalculadoraLayout = new javax.swing.GroupLayout(DesktopCalculadora);
        DesktopCalculadora.setLayout(DesktopCalculadoraLayout);
        DesktopCalculadoraLayout.setHorizontalGroup(
            DesktopCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopCalculadoraLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DesktopCalculadoraLayout.setVerticalGroup(
            DesktopCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopCalculadoraLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuOperacoes.setText("Calcular");

        opcaoMenu_UmNumero.setText("Com um número");
        opcaoMenu_UmNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMenu_UmNumeroActionPerformed(evt);
            }
        });
        MenuOperacoes.add(opcaoMenu_UmNumero);

        opcaoMenu_DoisNumeros.setText("Com dois números");
        opcaoMenu_DoisNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMenu_DoisNumerosActionPerformed(evt);
            }
        });
        MenuOperacoes.add(opcaoMenu_DoisNumeros);

        BarraMenu.add(MenuOperacoes);

        MenuOpcoes.setText("Opções");

        opcaoMenu_Sair.setText("Sair");
        opcaoMenu_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMenu_SairActionPerformed(evt);
            }
        });
        MenuOpcoes.add(opcaoMenu_Sair);

        opcaoMenu_Sobre.setText("Sobre");
        opcaoMenu_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoMenu_SobreActionPerformed(evt);
            }
        });
        MenuOpcoes.add(opcaoMenu_Sobre);

        BarraMenu.add(MenuOpcoes);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCalculadora)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCalculadora)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcaoMenu_UmNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMenu_UmNumeroActionPerformed
        Tela_OperacaoUmNumero t1 = new Tela_OperacaoUmNumero();
                
        int numeroInternaFrames = DesktopCalculadora.getAllFrames().length;
        
        if(numeroInternaFrames == 0){
            DesktopCalculadora.add(t1);
            t1.setVisible(true);
        }
        
    }//GEN-LAST:event_opcaoMenu_UmNumeroActionPerformed

    private void opcaoMenu_DoisNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMenu_DoisNumerosActionPerformed
        Tela_OperacaoDoisNumeros t1 = new Tela_OperacaoDoisNumeros();
                
        int numeroInternaFrames = DesktopCalculadora.getAllFrames().length;
        
        if(numeroInternaFrames == 0){
            DesktopCalculadora.add(t1);
            t1.setVisible(true);
        }
        
    }//GEN-LAST:event_opcaoMenu_DoisNumerosActionPerformed

    private void opcaoMenu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMenu_SairActionPerformed
         System.exit(WIDTH);
    }//GEN-LAST:event_opcaoMenu_SairActionPerformed

    private void opcaoMenu_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoMenu_SobreActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Programa desenvolvido por Willian Keji Yamashita Rosa"
                + "\nData: 07/02/2018"
                + "\nDesenvolvido no Netbeans"
                + "\nIntuito: Portfólio");
    }//GEN-LAST:event_opcaoMenu_SobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JDesktopPane DesktopCalculadora;
    private javax.swing.JMenu MenuOpcoes;
    private javax.swing.JMenu MenuOperacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem opcaoMenu_DoisNumeros;
    private javax.swing.JMenuItem opcaoMenu_Sair;
    private javax.swing.JMenuItem opcaoMenu_Sobre;
    private javax.swing.JMenuItem opcaoMenu_UmNumero;
    // End of variables declaration//GEN-END:variables
}
