/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interna;

import Classe.Calculadora;
import javax.swing.JOptionPane;

/**
 *
 * @author williank
 */
public class Tela_OperacaoDoisNumeros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_OperacaoDoisNumeros
     */
    public Tela_OperacaoDoisNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelDoisNumeros = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        PanelOperacaoDois_Numeros = new javax.swing.JPanel();
        labelN1_dois = new javax.swing.JLabel();
        labeln1_dois = new javax.swing.JLabel();
        campoN1_dois = new javax.swing.JFormattedTextField();
        campoN2_dois = new javax.swing.JFormattedTextField();
        ButtonMultiplicar = new javax.swing.JButton();
        ButtonDividir = new javax.swing.JButton();
        ButtonDiminur = new javax.swing.JButton();
        ButtonSomar = new javax.swing.JButton();
        PainelOperacaoDois_Resultado = new javax.swing.JPanel();
        campoResultado_dois = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        PainelDoisNumeros.setBorder(new javax.swing.border.MatteBorder(null));

        labelTitulo.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Operação com dois números");

        PanelOperacaoDois_Numeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Números"));
        PanelOperacaoDois_Numeros.setToolTipText("Números");

        labelN1_dois.setText("Nº 1");

        labeln1_dois.setText("Nº 2");

        campoN1_dois.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        campoN2_dois.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout PanelOperacaoDois_NumerosLayout = new javax.swing.GroupLayout(PanelOperacaoDois_Numeros);
        PanelOperacaoDois_Numeros.setLayout(PanelOperacaoDois_NumerosLayout);
        PanelOperacaoDois_NumerosLayout.setHorizontalGroup(
            PanelOperacaoDois_NumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperacaoDois_NumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperacaoDois_NumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOperacaoDois_NumerosLayout.createSequentialGroup()
                        .addComponent(labeln1_dois)
                        .addGap(18, 18, 18)
                        .addComponent(campoN2_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelOperacaoDois_NumerosLayout.createSequentialGroup()
                        .addComponent(labelN1_dois)
                        .addGap(18, 18, 18)
                        .addComponent(campoN1_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelOperacaoDois_NumerosLayout.setVerticalGroup(
            PanelOperacaoDois_NumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperacaoDois_NumerosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelOperacaoDois_NumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoN1_dois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelN1_dois))
                .addGap(18, 18, 18)
                .addGroup(PanelOperacaoDois_NumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeln1_dois)
                    .addComponent(campoN2_dois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ButtonMultiplicar.setText("Multiplicar");
        ButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicarActionPerformed(evt);
            }
        });

        ButtonDividir.setText("Dividir");
        ButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDividirActionPerformed(evt);
            }
        });

        ButtonDiminur.setText("Diminuir");
        ButtonDiminur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiminurActionPerformed(evt);
            }
        });

        ButtonSomar.setText("Somar");
        ButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomarActionPerformed(evt);
            }
        });

        PainelOperacaoDois_Resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        campoResultado_dois.setEditable(false);
        campoResultado_dois.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        campoResultado_dois.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoResultado_dois.setToolTipText("");

        javax.swing.GroupLayout PainelOperacaoDois_ResultadoLayout = new javax.swing.GroupLayout(PainelOperacaoDois_Resultado);
        PainelOperacaoDois_Resultado.setLayout(PainelOperacaoDois_ResultadoLayout);
        PainelOperacaoDois_ResultadoLayout.setHorizontalGroup(
            PainelOperacaoDois_ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOperacaoDois_ResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoResultado_dois)
                .addContainerGap())
        );
        PainelOperacaoDois_ResultadoLayout.setVerticalGroup(
            PainelOperacaoDois_ResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOperacaoDois_ResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoResultado_dois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Exponencial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelDoisNumerosLayout = new javax.swing.GroupLayout(PainelDoisNumeros);
        PainelDoisNumeros.setLayout(PainelDoisNumerosLayout);
        PainelDoisNumerosLayout.setHorizontalGroup(
            PainelDoisNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelDoisNumerosLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(PanelOperacaoDois_Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelDoisNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDoisNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDoisNumerosLayout.createSequentialGroup()
                        .addComponent(ButtonSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ButtonDiminur, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ButtonMultiplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(PainelOperacaoDois_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelDoisNumerosLayout.setVerticalGroup(
            PainelDoisNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDoisNumerosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelOperacaoDois_Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(PainelOperacaoDois_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PainelDoisNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSomar)
                    .addComponent(ButtonDiminur)
                    .addComponent(ButtonDividir)
                    .addComponent(ButtonMultiplicar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(PainelDoisNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(PainelDoisNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomarActionPerformed
        try{
            String campo1 = campoN1_dois.getText();
            String campo2 = campoN2_dois.getText();

            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 1 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else if(campo2.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 2 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
               Calculadora c1 = new Calculadora();

               c1.setNumero1(Double.parseDouble(campo1));
               c1.setNumero2(Double.parseDouble(campo2));

               String soma = ""+c1.somar()+"";
               campoResultado_dois.setText(soma);    
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonSomarActionPerformed

    private void ButtonDiminurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiminurActionPerformed
        try{
            String campo1 = campoN1_dois.getText();
            String campo2 = campoN2_dois.getText();

            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 1 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else if(campo2.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 2 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campoN1_dois.getText()));
                c1.setNumero2(Double.parseDouble(campoN2_dois.getText()));

                String subtracao = ""+c1.diminuir()+"";
                campoResultado_dois.setText(subtracao);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonDiminurActionPerformed

    private void ButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDividirActionPerformed
        try{
            String campo1 = campoN1_dois.getText();
            String campo2 = campoN2_dois.getText();

            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 1 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else if(campo2.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 2 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campoN1_dois.getText()));
                c1.setNumero2(Double.parseDouble(campoN2_dois.getText()));

                String dividir = ""+c1.dividir()+"";
                campoResultado_dois.setText(dividir);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ButtonDividirActionPerformed

    private void ButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicarActionPerformed
        try{
            String campo1 = campoN1_dois.getText();
            String campo2 = campoN2_dois.getText();

            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 1 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else if(campo2.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 2 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campoN1_dois.getText()));
                c1.setNumero2(Double.parseDouble(campoN2_dois.getText()));

                String multiplicar = ""+c1.multiplicar()+"";
                campoResultado_dois.setText(multiplicar);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonMultiplicarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String campo1 = campoN1_dois.getText();
            String campo2 = campoN2_dois.getText();

            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 1 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else if(campo2.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número 2 está vazio", 
                                "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campoN1_dois.getText()));
                c1.setNumero2(Double.parseDouble(campoN2_dois.getText()));

                String exponecial = ""+c1.calcularExponecial()+"";
                campoResultado_dois.setText(exponecial);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDiminur;
    private javax.swing.JButton ButtonDividir;
    private javax.swing.JButton ButtonMultiplicar;
    private javax.swing.JButton ButtonSomar;
    private javax.swing.JPanel PainelDoisNumeros;
    private javax.swing.JPanel PainelOperacaoDois_Resultado;
    private javax.swing.JPanel PanelOperacaoDois_Numeros;
    private javax.swing.JFormattedTextField campoN1_dois;
    private javax.swing.JFormattedTextField campoN2_dois;
    private javax.swing.JTextField campoResultado_dois;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelN1_dois;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labeln1_dois;
    // End of variables declaration//GEN-END:variables
}
