/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interna;

import Classe.Calculadora;
import javax.swing.JOptionPane;

/**
 *
 * @author williank
 */
public class Tela_OperacaoUmNumero extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_OperacaoUmNumero
     */
    public Tela_OperacaoUmNumero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelUmNumero = new javax.swing.JPanel();
        PainelUmNumero_numeros = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoN1_um = new javax.swing.JFormattedTextField();
        PainelUmNumero_resultado = new javax.swing.JPanel();
        campoResultado_um = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ButtonFatorial = new javax.swing.JButton();
        ButtonFibonacci = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        PainelUmNumero.setBorder(new javax.swing.border.MatteBorder(null));

        PainelUmNumero_numeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Números"));
        PainelUmNumero_numeros.setToolTipText("Números");

        jLabel5.setText("Nº 1");

        campoN1_um.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout PainelUmNumero_numerosLayout = new javax.swing.GroupLayout(PainelUmNumero_numeros);
        PainelUmNumero_numeros.setLayout(PainelUmNumero_numerosLayout);
        PainelUmNumero_numerosLayout.setHorizontalGroup(
            PainelUmNumero_numerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUmNumero_numerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(campoN1_um, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        PainelUmNumero_numerosLayout.setVerticalGroup(
            PainelUmNumero_numerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUmNumero_numerosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PainelUmNumero_numerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoN1_um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PainelUmNumero_resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        campoResultado_um.setEditable(false);
        campoResultado_um.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoResultado_um.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoResultado_um.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout PainelUmNumero_resultadoLayout = new javax.swing.GroupLayout(PainelUmNumero_resultado);
        PainelUmNumero_resultado.setLayout(PainelUmNumero_resultadoLayout);
        PainelUmNumero_resultadoLayout.setHorizontalGroup(
            PainelUmNumero_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUmNumero_resultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(campoResultado_um)
                .addContainerGap())
        );
        PainelUmNumero_resultadoLayout.setVerticalGroup(
            PainelUmNumero_resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUmNumero_resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoResultado_um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Operação com um número");

        javax.swing.GroupLayout PainelUmNumeroLayout = new javax.swing.GroupLayout(PainelUmNumero);
        PainelUmNumero.setLayout(PainelUmNumeroLayout);
        PainelUmNumeroLayout.setHorizontalGroup(
            PainelUmNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelUmNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelUmNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelUmNumero_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUmNumeroLayout.createSequentialGroup()
                        .addGap(0, 111, Short.MAX_VALUE)
                        .addComponent(PainelUmNumero_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)))
                .addContainerGap())
        );
        PainelUmNumeroLayout.setVerticalGroup(
            PainelUmNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUmNumeroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PainelUmNumero_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(PainelUmNumero_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonFatorial.setText("Calcular Fatorial");
        ButtonFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFatorialActionPerformed(evt);
            }
        });

        ButtonFibonacci.setText("Calcular Fibonacci");
        ButtonFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFibonacciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PainelUmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelUmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonFatorial)
                    .addComponent(ButtonFibonacci))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFatorialActionPerformed
        try{
            String campo1 = campoN1_um.getText();
            
            if(campo1.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número está vázio", 
                            "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campo1));

                int numero = (int) c1.getNumero1();
                if(numero <= 20){
                    String fatorial = ""+c1.fatorial(numero)+"";
                    campoResultado_um.setText(fatorial);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERRO!\nO número é muito grande para operação."
                            + "\nNúmero máximo aceito: 20", 
                            "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonFatorialActionPerformed

    private void ButtonFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFibonacciActionPerformed
        
        try{
            String campo1 = campoN1_um.getText();
            
            if(campo1.isEmpty()){
              JOptionPane.showMessageDialog(rootPane, "ERRO!\nO valor do número está vázio", 
                            "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
            }else{
                Calculadora c1 = new Calculadora();
                c1.setNumero1(Double.parseDouble(campo1));

                int numero = (int) c1.getNumero1();

                if(numero <= 48){
                String fibonacci = ""+c1.calcularFibonacci(numero)+"";
                campoResultado_um.setText(fibonacci);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERRO!\nO número muito grande...Isto vai gerar sobrecarga no programa.", 
                    "ATENÇÃO!",JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ButtonFibonacciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonFatorial;
    private javax.swing.JButton ButtonFibonacci;
    private javax.swing.JPanel PainelUmNumero;
    private javax.swing.JPanel PainelUmNumero_numeros;
    private javax.swing.JPanel PainelUmNumero_resultado;
    private javax.swing.JFormattedTextField campoN1_um;
    private javax.swing.JFormattedTextField campoResultado_um;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
